#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"
  source normalize

  git branch -vv | awk '$1 == "*" { $1=""; $2=""; print }'

}

source sub "$BASH_SOURCE" "$@"
