#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"
  source normalize  

  cd "$HOME"
  git grep cache.nih | grep template: | grep -v exec/ | cut -d: -f1 | uniq | runmany 'rm -f ${1%.template}'
}

source sub "$BASH_SOURCE" "$@"
