#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"
  source normalize  

  local many="${1:-10}"
  
  block runmany "$many" 'cd $1 && git pull' || true
  block clone
  if [[ -f "Blockfile.lock" ]]; then
    block lock
  fi
  home status
}

source sub "$BASH_SOURCE" "$@"
