#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"
  source normalize
  
  local nm_key="${1:-$(cat "$(find .git-crypt -name "*$(gpg2 --card-status | grep 'Signature key' | awk '{print $(NF-1) $(NF)}')*")" | gpg)}"
  git crypt unlock "$nm_key"
}

source sub "$BASH_SOURCE" "$@"
