#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"
  source normalize

  local many="${1:-10}"
  
  block runmany "$many" 'echo $1 $(cd $1 && gs)' | sort -k4 | talign 3
}

source sub "$BASH_SOURCE" "$@"
