#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"
  source normalize

  mkdir -p /config/ssh
  cp ~/.ssh/authorized_keys /config/ssh/authorized_keys

  mkdir -p /config/git
  cp ~/.gitconfig /config/git/config
}

source sub "$BASH_SOURCE" "$@"
