#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"
  source "$_block_home/script/profile" ''
  source normalize
  
  pushd "$shome" >/dev/null
  require
  popd >/dev/null

  local nm_org="$1"; shift

  local fl_ssh
  if [[ "${1:-}" == "ssh" ]]; then
    fl_ssh="$1"; shift
  fi

  (
    env -u AWS_VAULT fogg assume "$nm_org" imma credentials config | ssh "$@" tee .aws/credentials.tmp >/dev/null
    ssh "$@" mv -f .aws/credentials.tmp .aws/credentials
  ) &

  if [[ -n "$fl_ssh" ]]; then
    ssh "$@"
  fi

  wait
}

source sub "$BASH_SOURCE" "$@"
