#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"
  source normalize
  
  block lock
  git add Blockfile.lock
  git diff --cached
  if [[ -n "${1:-}" ]]; then
    git commit -m "$1"
  else
    git commit -v
  fi
}

source sub "$BASH_SOURCE" "$@"
