#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"
  source normalize
  
  local nm_key="${1:-$(gpg2 --card-status | grep 'Signature key' | awk '{print $(NF-1) $(NF)}')}"
  git crypt unlock <(cat "$(find .git-crypt -name "*${nm_key}*")" | gpg2)
}

source sub "$BASH_SOURCE" "$@"
