#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"
  source normalize  

  local many="${1:-10}"
  
  runmany "$many" 'cd $1 && git pull' work/*/
}

source sub "$BASH_SOURCE" "$@"
